---
language: python
services: docker

env:
  global:
    - ROLE_NAME: vmware-exporter
  matrix:
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: debian9
    - MOLECULE_DISTRO: debian10

install:
  # Install test dependencies.
  - pip install molecule docker

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv ansible-$ROLE_NAME scalair.$ROLE_NAME
  - cd scalair.$ROLE_NAME

script:
  # Run tests.
  - molecule test
