---
- name: Debian - Ensure gcc, python3 and pip3 are installed
  apt:
    name:
      - gcc
      - python-setuptools
      - python3
      - python3-dev
      - python3-pip
    state: present

- name: Ensure vmware_exporter is installed (via pip3)
  pip:
    name: vmware_exporter
    executable: /usr/bin/pip3
    state: present
