---
# Setup/install tasks.
- include_tasks: RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: Debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: install.yml

- include_tasks: configure.yml
